<a href="https://colab.research.google.com/github/AnnaAsritha/Dap-files/blob/main/numpy_concat%2C_stack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

print("arr1=", arr1) 

arr2 = np.array([[5, 6], [7, 8]])

print("arr2=", arr2) 

print("after concatenation =")

arr = np.concatenate((arr1, arr2), axis=1) #0=row, 1=col

print(arr) 

arr1= [[1 2]
 [3 4]]
arr2= [[5 6]
 [7 8]]
after concatenation =
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

print("arr1=", arr1) 

arr2 = np.array([[5, 6], [7, 8]])

print("arr2=", arr2) 

print("after concatenation =")
arr = np.concatenate((arr1, arr2), axis=0) #0=row, 1=col

print(arr) 

arr1= [[1 2]
 [3 4]]
arr2= [[5 6]
 [7 8]]
after concatenation =
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print("hstack =", np.hstack((a,b)))

print("vstack =", np.vstack((a,b)))

a = np.array([[1],[2],[3]])

b = np.array([[4],[5],[6]])

print("hstack =", np.hstack((a,b)))

print("vstack =", np.vstack((a,b)))


hstack = [1 2 3 4 5 6]
vstack = [[1 2 3]
 [4 5 6]]
hstack = [[1 4]
 [2 5]
 [3 6]]
vstack = [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
a = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])

b = np.array([[7,8,9],[77,88,99],[777,888,999],[7777,8888,9999]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))

arr = np.concatenate((a, b), axis=0)

print("\n======next print======")

print("\n concatenate at axis 0=\n",arr)

arr1 = np.concatenate((a, b), axis=1)

print("\n======next print======")

print("\n concatenate at axis 1=\n",arr1)


hstack =
 [[   1    2    3    7    8    9]
 [  11   22   33   77   88   99]
 [ 111  222  333  777  888  999]
 [1111 2222 3333 7777 8888 9999]]

======next print======

vstack =
 [[   1    2    3]
 [  11   22   33]
 [ 111  222  333]
 [1111 2222 3333]
 [   7    8    9]
 [  77   88   99]
 [ 777  888  999]
 [7777 8888 9999]]

======next print======

 concatenate at axis 0=
 [[   1    2    3]
 [  11   22   33]
 [ 111  222  333]
 [1111 2222 3333]
 [   7    8    9]
 [  77   88   99]
 [ 777  888  999]
 [7777 8888 9999]]

======next print======

 concatenate at axis 1=
 [[   1    2    3    7    8    9]
 [  11   22   33   77   88   99]
 [ 111  222  333  777  888  999]
 [1111 2222 3333 7777 8888 9999]]


In [ ]:
a= np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = np.array([7,8,9])
print(b)

[7 8 9]


In [ ]:
c = np.array([[7,8,9]])
print(c)

[[7 8 9]]


In [ ]:
np.append(a,b, axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.append(a,c, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6])
np.concatenate((a,b))

array([1, 2, 3, 5, 6])

In [ ]:
np.r_[a,b]

array([1, 2, 3, 5, 6])

In [ ]:
a = np.array([1, 2,3])
b = np.array([5, 6,7])
np.stack([a,b]).reshape(-1)

array([1, 2, 3, 5, 6, 7])

In [ ]:
a = np.array([1, 2,3])
b = np.array([5, 6,7])
np.stack([a,b])

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
print()

In [ ]:
a = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])

b = np.array([[7,8,9],[77,88,99],[777,888,999],[7777,8888,9999]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[   1    2    3    7    8    9]
 [  11   22   33   77   88   99]
 [ 111  222  333  777  888  999]
 [1111 2222 3333 7777 8888 9999]]

======next print======

vstack =
 [[   1    2    3]
 [  11   22   33]
 [ 111  222  333]
 [1111 2222 3333]
 [   7    8    9]
 [  77   88   99]
 [ 777  888  999]
 [7777 8888 9999]]


In [ ]:
a = np.array([[1],[2],[3]])

b = np.array([[8],[9],[10]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[ 1  8]
 [ 2  9]
 [ 3 10]]

======next print======

vstack =
 [[ 1]
 [ 2]
 [ 3]
 [ 8]
 [ 9]
 [10]]


In [ ]:
a = np.array([[1,2],[3,4]])

b = np.array([[5,6],[7,8]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[1 2 5 6]
 [3 4 7 8]]

======next print======

vstack =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
bb= np.array([[5, 6],[7,8]])
cc=b.T

print("vstack=",np.vstack((a,cc)))

print("hstack=",np.hstack((a,bb)))

vstack= [[1 2]
 [3 4]
 [5 6]]
hstack= [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.array((1,2,3))
b = np.array((7,8,9))
print(a)
print(b)

print("vstack\n")
print(np.vstack((a,b)))
print("concatenate\n")
print(np.concatenate([a.reshape(1,3),b.reshape(1,3)]))
print("stack\n")
print(np.stack((a,b),axis=1))
print("concatenate\n")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 1))
print("stack\n")
print(np.stack((a,b),axis=0))
print("concatenate\n")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 0))

[1 2 3]
[7 8 9]
vstack

[[1 2 3]
 [7 8 9]]
concatenate

[[1 2 3]
 [7 8 9]]
stack

[[1 7]
 [2 8]
 [3 9]]
concatenate

[[1 2 3 7 8 9]]
stack

[[1 2 3]
 [7 8 9]]
concatenate

[[1 2 3]
 [7 8 9]]
